### ISSUE TITLE
Replace `from_obj` with a dispatched function

### ISSUE THREAD

**Issue by josephwillard** [pymc-devs/symbolic-pymc#14]
Looking through the code I found this as a todo item, what are your thoughts on approaching this?

**Comment by brandonwillard** [comment]
Basically, instead of finding appropriate (and implemented) meta MRO for any given object through recursion in `MetaSymbol.from_obj`, it might be cleaner to use `multipledispatch` to do the same thing.  This requires a new generic function implementation for each `MetaSymbol` class, which I believe can be easily automated in `MetaSymbolType.__new__`.
