### ISSUE TITLE
mt.random.normal does not work with logic variables

### ISSUE THREAD

**Issue by josephwillard** [pymc-devs/symbolic-pymc#51]
Running the following code,

```
from unification import unify
from symbolic_pymc.tensorflow.meta import mt

with graph_mode():
    mt.random.normal(mean=0, stddev=1, shape=(1000,),  name=var())
```

produces the following error,

```
TypeError                                 Traceback (most recent call last)
<ipython-input-17-cad0f77f3b2c> in <module>
----> 1 import codecs, os;__pyfile = codecs.open('''/tmp/py8439WvU''', encoding='''utf-8''');__code = __pyfile.read().encode('''utf-8''');__pyfile.close();os.remove('''/tmp/py8439WvU''');exec(compile(__code, '''/home/joseph/git_projects/josephwillard.github.io/org_files/blog_4.org[*Org Src blog_4.org[ python ]*]''', 'exec'));

~/git_projects/josephwillard.github.io/org_files/blog_4.org[*Org Src blog_4.org[ python ]*] in <module>

~/git_projects/symbolic-pymc/symbolic_pymc/tensorflow/meta.py in meta_obj(*args, **kwargs)
    821                     args = [o.reify() if hasattr(o, "reify") else o for o in args]
    822                     res = ns_obj(*args, **kwargs)
--> 823                     return metatize(res)
    824 
    825         elif isinstance(ns_obj, types.ModuleType):

~/anaconda3/envs/symbolic-pymc/lib/python3.6/site-packages/tensorflow/python/ops/random_ops.py in random_normal(shape, mean, stddev, dtype, seed, name)
     72     A tensor of the specified shape filled with random normal values.
     73   """
---> 74   with ops.name_scope(name, "random_normal", [shape, mean, stddev]) as name:
     75     shape_tensor = _ShapeTensor(shape)
     76     mean_tensor = ops.convert_to_tensor(mean, dtype=dtype, name="mean")

~/anaconda3/envs/symbolic-pymc/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in __enter__(self)
   6197       try:
   6198         self._name_scope = g.name_scope(self._name)
-> 6199         return self._name_scope.__enter__()
   6200       except:
   6201         self._g_manager.__exit__(*sys.exc_info())

~/anaconda3/envs/symbolic-pymc/lib/python3.6/contextlib.py in __enter__(self)
     79     def __enter__(self):
     80         try:
---> 81             return next(self.gen)
     82         except StopIteration:
     83             raise RuntimeError("generator didn't yield") from None

~/anaconda3/envs/symbolic-pymc/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in name_scope(self, name)
   3993         # Scopes created in the root must match the more restrictive
   3994         # op name regex, which constrains the initial character.
-> 3995         if not _VALID_OP_NAME_REGEX.match(name):
   3996           raise ValueError("'%s' is not a valid scope name" % name)
   3997     old_stack = self._name_stack

TypeError: expected string or bytes-like object

```

**Comment by brandonwillard** [comment]
`mt.random.normal` is a wrapper function generated by `mt`.  You can tell by inspecting the type returned by `mt.random.normal`.  [`mt` produces these kinds of functions when it can't find an `OpDef` from which it can obtain a meta `TFlowMetaOpDef`](https://github.com/pymc-devs/symbolic-pymc/blob/master/symbolic_pymc/tensorflow/meta.py#L813) (and return that).  These wrapper functions basically execute the underlying `tf.*` function and convert the results to a meta object.

This is why logic variables won't work as arguments to `mt.random.normal`; it's simply `tf.random.normal`, and that can't take logic variables.  We should probably remove this wrapper functionality, since it's a little confusing and rarely useful.

Otherwise, the base function, `tf.random.normal`, is a "graph generator" function.  These helper functions create graphs using core TF functions that are more closely aligned with the `OpDef`s that actually appear in TF graphs.

If you inspect the source for `tf.random.normal`, you'll see that the actual `OpDef` for a standard normal random variable is created by `gen_random_ops.random_standard_normal` and, from inspection of that, you can see it has the name `RandomStandardNormal`.

The question is now "How do we get [`mt` to produce] a `TFlowMetaOpDef` for `RandomStandardNormal?"

`mt` has very rudimentary means of producing `TFlowMetaOpDef`s from helper function names like (e.g. `add`, `matmul`, etc.), and that takes place in [`mt.find_opdef`](https://github.com/pymc-devs/symbolic-pymc/blob/master/symbolic_pymc/tensorflow/meta.py#L786).  In this case, `mt.find_opdef('RandomStandardNormal')` returns `None` and, as a result, `mt.RandomStandardNormal` produces another one of those unhelpful wrapper functions.

The problem here is that the `mt.find_opdef` isn't finding an entry for `RandomStandardNormal` in the map `symbolic_pymc.tensorflow.meta.op_def_lib.lower_op_name_to_raw`.  That map is simply a more consistent way to infer the underlying `OpDef` names for Python helper functions (e.g. camel-case names like `tf.argmax` to `ArgMax`).  Unfortunately, this doesn't work for snake-case naming, but we could easily add it (e.g. by converting to camel-case, or removing underscores, and checking for the existence of a corresponding `OpDef` in `tensorflow.python.framework.op_def_registry`). 

Otherwise, `mt.find_opdef` should probably perform the [`op_def_registry.get_registered_ops()` look-up](https://github.com/pymc-devs/symbolic-pymc/blob/master/symbolic_pymc/tensorflow/meta.py#L790) on `name` if doesn't find anything in `op_def_lib.lower_op_name_to_raw`.  That way, `mt` would always return the corresponding `TFlowMetaOpDef` when you attempt to access the name of a valid `OpDef`.

In the meantime, you can get the desired `TFlowMetaOpDef` from `mt.randomstandardnormal`.
